[tool.poetry]
name = "art_graph"
version = "0.1.4"
description = "Tools for creating and analyzing art graphs"
authors = ["Reuben Brasher <rkbrasher@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "art_graph"}]
include = ["README.md", "art_graph/tests/test_data/*"]

[tool.poetry.dependencies]
python = "^3.10"
poetry = "^1.8"
pytest = "^8.2"
black = "^24.4"
numpy = "^1.26.4"
pandas = "^2.2.2"
networkx = "^3.3"
cinemagoer = "^2023.5.1"
requests = "^2.31.0"
gensim = "^4.3.2"
tqdm = "^4.66.4"
pydantic = "^2.7.3"
psycopg2-binary = "^2.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
